env:
  TERM: 'xterm-256color'

window:
  decorations: none

scrolling:
  history: 100000

font:
  normal:
    family: UbuntuMono Nerd Font
    style: Regular

  bold:
    family: UbuntuMono Nerd Font
    style: Bold 

  italic:
    family: UbuntuMono Nerd Font
    style: Italic

  bold_italic:
    family: UbuntuMono Nerd Font
    style: Bold Italic

  size: 14.0
    #
# github Alacritty Colors
colors:
  # Default colors
  primary:
    background: '0x24292e'
    foreground: '0xd1d5da'

  # Normal colors
  normal:
    black:   '0x24292e'
    red:     '0xf14c4c'
    green:   '0x23d18b'
    yellow:  '0xe2e210'
    blue:    '0x3b8eea'
    magenta: '0xbc3fbc'
    cyan:    '0x29b7da'
    white:   '0xd1d5da'

  # Bright colors
  bright:
    black:   '0x666666'
    red:     '0xf14c4c'
    green:   '0x23d18b'
    yellow:  '0xf5f543'
    blue:    '0x3b8eea'
    magenta: '0xd670d6'
    cyan:    '0x29b7da'
    white:   '0xd1d5da'

  indexed_colors:
    - { index: 16, color: '0xd18616' }
    - { index: 17, color: '0xf14c4c' }

bell:
  animation: EaseOutExpo

background_opacity: 0.92

cursor:
  style:
    shape: Beam
