timeout: 5

wallpaper: boot():/wallpapers/1.jpeg
wallpaper: boot():/wallpapers/2.jpeg
wallpaper: boot():/wallpapers/3.jpeg
wallpaper: boot():/wallpapers/4.jpeg
wallpaper: boot():/wallpapers/5.jpeg
wallpaper_style: stretched

/Arch Linux
    protocol: linux
    kernel_path: boot():/vmlinuz-linux
    cmdline: root=UUID=d498cfbe-3bf3-49ef-8602-f54720b90aa6 rw quiet loglevel=3 intel_iommu=on
    module_path: boot():/initramfs-linux.img

/Arch Linux (fallback initramfs)
    protocol: linux
    kernel_path: boot():/vmlinuz-linux
    cmdline: root=UUID=d498cfbe-3bf3-49ef-8602-f54720b90aa6 rw quiet loglevel=3 intel_iommu=on
    module_path: boot():/initramfs-linux-fallback.img
