#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  vars:
    ansible_ask_become_pass: true

  tasks:
  - name: "Create symlink for NeoVim configuration"
    ansible.builtin.file:
      src: "{{ playbook_dir }}/alacritty"
      dest: ~/.config/alacritty
      state: link
      owner: 1000
      group: 1000

  - name: "Install Common GUI tools"
    community.general.pacman:
      name: 
      - alacritty
      update_cache: yes
      state: latest
    become: yes

  - name: "Install Opera"
    community.general.pacman:
      name: 
      - opera
      - opera-ffmpeg-codecs
      state: latest
    become: yes
...
