#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  vars:
    ansible_ask_become_pass: true
    configs:
    - alacritty
    - lf
    - mpv
    - pass-git-helper
    - flameshot
    - zathura

  tasks:
  - name: "Create symlink for NeoVim configuration"
    ansible.builtin.file:
      src: "{{ playbook_dir }}/config/{{ item }}"
      dest: "~/.config/{{ item }}"
      state: link
      owner: 1000
      group: 1000
    loop: "{{ configs }}"

  - name: "Apps from AUR"
    kewlfft.aur.aur:
      name: lf-bin
      state: latest
    become: yes
    become_user: aur_builder

  - name: "Install Common GUI tools"
    community.general.pacman:
      name: 
      - alacritty
      - flameshot
      - gparted
      - mpv
      - zathura
      - zathura-pdf-mupdf
      - zathura-ps
      update_cache: yes
      state: latest
    become: yes

  - name: "Install Pass"
    community.general.pacman:
      name: 
      - pass
      - pass-otp
      state: latest
    become: yes

  - name: "Install pass-git-helper"
    kewlfft.aur.aur:
      name: pass-git-helper
      state: latest
    become: yes
    become_user: aur_builder

  - name: "Install Opera"
    community.general.pacman:
      name: 
      - opera
      - opera-ffmpeg-codecs
      - browserpass
      - browserpass-chromium
      state: latest
    become: yes

  - name: "Make browserpass host config"
    make:
      chdir: /usr/lib/browserpass
      target: hosts-chrome-user

  - name: "Install Messengers"
    community.general.pacman:
      name: 
      - telegram-desktop
      - element-desktop
      state: latest
    become: yes

  - name: "Install Slack"
    kewlfft.aur.aur:
      name: slack-desktop
      state: latest
    become: yes
    become_user: aur_builder

  - name: "Install Skype"
    kewlfft.aur.aur:
      name: skypeforlinux-stable-bin
      state: latest
    become: yes
    become_user: aur_builder

  - name: "Install Thunderbird"
    community.general.pacman:
      name: 
      - thunderbird
      - thunderbird-i18n-ru
      - thunderbird-i18n-en-us
      state: latest
    become: yes

  - name: "Install Docker tools"
    community.general.pacman:
      name:
      - docker
      - helm
      - k9s
      - kubectl
      - kubectx
      state: latest
    become: yes

  - name: "Enable Docker"
    ansible.builtin.systemd:
      name: docker
      state: started
      enabled: yes
    become: yes

  - name: "Add current user to docker group"
    ansible.builtin.user:
      name: "{{ ansible_user_id }}"
      groups: docker
      append: yes
    become: yes

  - name: "Install Krew"
    kewlfft.aur.aur:
      name: krew
      state: latest
    become: yes
    become_user: aur_builder

  - name: "Install Google Cloud SDK"
    kewlfft.aur.aur:
      name: google-cloud-sdk
      state: present
    become: yes
    become_user: aur_builder

  - name: "Install tfswitch"
    kewlfft.aur.aur:
      name: tfswitch-bin
      state: latest
    become: yes
    become_user: aur_builder

  - name: "Install Postman"
    kewlfft.aur.aur:
      name: postman-bin
      state: latest
    become: yes
    become_user: aur_builder

  - name: "Install Git Extras"
    kewlfft.aur.aur:
      name: git-extras
      state: latest
    become: yes
    become_user: aur_builder

  - name: "Install Transmission"
    community.general.pacman:
      name:
      - transmission-cli
      state: latest
    become: yes
...
