#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  vars:
    ansible_ask_become_pass: true
    configs:
    - alacritty
    - lf

  tasks:
  - name: "Create symlink for NeoVim configuration"
    ansible.builtin.file:
      src: "{{ playbook_dir }}/{{ item }}"
      dest: "~/.config/{{ item }}"
      state: link
      owner: 1000
      group: 1000
    loop: "{{ configs }}"

  - name: "Apps from AUR"
    kewlfft.aur.aur:
      name: lf-bin
      state: latest
    become: yes
    become_user: aur_builder

  - name: "Install Common GUI tools"
    community.general.pacman:
      name: 
      - alacritty
      - flameshot
      update_cache: yes
      state: latest
    become: yes

  - name: "Install Opera"
    community.general.pacman:
      name: 
      - opera
      - opera-ffmpeg-codecs
      state: latest
    become: yes

  - name: "Install Messengers"
    community.general.pacman:
      name: 
      - telegram-desktop
      - element-desktop
      state: latest
    become: yes

  - name: "Install Slack"
    kewlfft.aur.aur:
      name: slack-desktop
      state: latest
    become: yes
    become_user: aur_builder

  - name: "Install Skype"
    kewlfft.aur.aur:
      name: skypeforlinux-stable-bin
      state: latest
    become: yes
    become_user: aur_builder

  - name: "Install Thunderbird"
    community.general.pacman:
      name: 
      - thunderbird
      - thunderbird-i18n-ru
      - thunderbird-i18n-en-us
      state: latest
    become: yes

  - name: "Install k8s tools"
    community.general.pacman:
      name:
      - kubectl
      - kubectx
      - k9s
      state: latest
    become: yes

  - name: "Install Google Cloud SDK"
    kewlfft.aur.aur:
      name: google-cloud-sdk
      state: latest
    become: yes
    become_user: aur_builder
...
