#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  vars:
    ansible_ask_become_pass: yes

  tasks:
  - name: "Install Pipewire"
    community.general.pacman:
      name: 
      - pipewire
      - pipewire-alsa
      - wireplumber
      - helvum
      state: latest
    become: yes
...
