#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  vars:
    ansible_ask_become_pass: true

  tasks:
  - name: "Disable PC speaker in console"
    ansible.builtin.replace:
      path: /etc/inputrc
      regexp: '^#(set bell-style none)$'
      replace: '\1' 
    become: yes

  - name: "Create symlink for Git configuration"
    ansible.builtin.file:
      src: "{{ playbook_dir }}/git"
      dest: ~/.config/git
      state: link
      owner: 1000
      group: 1000

  - name: "Create symlink for NeoVim configuration"
    ansible.builtin.file:
      src: "{{ playbook_dir }}/nvim"
      dest: ~/.config/nvim
      state: link
      owner: 1000
      group: 1000

  - name: "Create symlink for Tmux configuration"
    ansible.builtin.file:
      src: "{{ playbook_dir }}/tmux"
      dest: ~/.config/tmux
      state: link
      owner: 1000
      group: 1000

  - name: "Clone tmux-powerline"
    ansible.builtin.git:
      repo: 'https://github.com/erikw/tmux-powerline.git'
      dest: "~/.local/share/tmux-powerline"

  - name: "Install common packages"
    community.general.pacman:
      name: 
      - curl
      - neovim
      - ripgrep
      - which
      - exa
      - tmux
      - broot
      - bottom
      - bat
      - bash-completion
      - go-yq
      - fish
      - starship
      update_cache: yes
      state: latest
    become: yes

  - name: "Create symlink for Fish configuration"
    ansible.builtin.file:
      src: "{{ playbook_dir }}/fish"
      dest: ~/.config/fish
      state: link
      owner: 1000
      group: 1000

  - name: "Set fish as default shell for current user"
    ansible.builtin.user:
      name: "{{ ansible_user_id }}"
      shell: /usr/bin/fish
    become: yes

  - name: "Install LVM2"
    community.general.pacman:
      name: 
      - lvm2
      state: latest
    become: yes
...
