#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  vars:
    ansible_ask_become_pass: true
    configs:
    - fish
    - git
    - nvim
    - starship
    - tmux

  tasks:
  - name: "Disable PC speaker in console"
    ansible.builtin.replace:
      path: /etc/inputrc
      regexp: '^#(set bell-style none)$'
      replace: '\1' 
    become: yes

  - name: "Enable TimesyncD"
    ansible.builtin.systemd:
      name: systemd-timesyncd
      enabled: yes
    become: yes

  - name: "Upgrade all packages"
    community.general.pacman:
      update_cache: yes
      upgrade: yes
    become: yes

  - name: "Create symlink for configuration directories"
    ansible.builtin.file:
      src: "{{ playbook_dir }}/config/{{ item }}"
      dest: "~/.config/{{ item }}"
      state: link
      owner: 1000
      group: 1000
    loop: "{{ configs }}"

  - name: "Clone tmux-powerline"
    ansible.builtin.git:
      repo: 'https://github.com/erikw/tmux-powerline.git'
      dest: "~/.local/share/tmux-powerline"

  - name: "Install common packages"
    community.general.pacman:
      name: 
      - bash-completion
      - bat
      - bind
      - bottom
      - broot
      - curl
      - dust
      - exa
      - fd
      - fish
      - fisher
      - fzf
      - go-yq
      - hub
      - jq
      - lazygit
      - mediainfo
      - neovim
      - openbsd-netcat
      - openvpn
      - ripgrep
      - rmlint
      - rsync
      - starship
      - thefuck
      - tmux
      - unzip
      - wget
      - which
      update_cache: yes
      state: latest
    become: yes

  - name: "Set fish as default shell for current user"
    ansible.builtin.user:
      name: "{{ ansible_user_id }}"
      shell: /usr/bin/fish
    become: yes

  - name: "Install disk utilities"
    community.general.pacman:
      name: 
      - btrfs-progs
      - lvm2
      - mdadm
      - ntfs-3g
      - xfsprogs
      state: latest
    become: yes
...
