#!/usr/bin/env ansible-playbook
- hosts: localhost
  vars:
    ansible_ask_become_pass: true
    configs:
    - bat
    - fish
    - git
    - lazygit
    - lf
    - nvim
    - starship
    - tmux
    - tmux-powerline

  tasks:
  - name: "Disable PC speaker in console"
    ansible.builtin.replace:
      path: /etc/inputrc
      regexp: '^#(set bell-style none)$'
      replace: '\1'
    become: true

  - name: "Create stub link for resolv.conf"
    ansible.builtin.file:
      src: "/run/systemd/resolve/resolv.conf"
      dest: "/etc/resolv.conf"
      state: link
    become: true

  - name: "Enable TimesyncD"
    ansible.builtin.systemd:
      name: systemd-timesyncd
      enabled: yes
    become: true

  - name: "Upgrade all packages"
    community.general.pacman:
      update_cache: yes
      upgrade: yes
    become: true

  - name: "Create the `aur_builder` user"
    become: true
    ansible.builtin.user:
      name: aur_builder
      create_home: yes
      group: wheel

  - name: "Allow the `aur_builder` user to run `sudo pacman` without a password"
    become: true
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/11-install-aur_builder
      line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      create: yes
      validate: 'visudo -cf %s'

  - name: "Create symlink for configuration directories"
    ansible.builtin.file:
      src: "{{ playbook_dir }}/config/{{ item }}"
      dest: "~/.config/{{ item }}"
      state: link
      owner: 1000
      group: 1000
    loop: "{{ configs }}"

  - name: "Add usev rule for Dactyl"
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/config/udev/dactyl.rules"
      dest: /etc/udev/rules.d/92-viia.rules
      owner: root
      group: root
      mode: '0644'
    become: true

  - name: "Install common packages"
    community.general.pacman:
      name:
      - atool # A script for managing file archives of various types
      - bash-completion # Programmable completion for the bash shell
      - bat # Cat clone with syntax highlighting and git integration
      - bind # A complete, highly portable implementation of the DNS protocol
      - bottom # A graphical process/system monitor
      - broot # Fuzzy Search + tree + cd
      - btop # A monitor of system resources, bpytop ported to C++
      - curl # It's fucking cURL, questions?
      - difftastic # An experimental diff tool that compares files based on their syntax
      - dust # A more intuitive version of du in rust
      - eza # ls replacement
      - fd # Simple, fast and user-friendly alternative to find
      - fish # Smart and user friendly shell intended mostly for interactive use
      - fisher # A package manager for the fish shell
      - fzf # Command-line fuzzy finder
      - github-cli # The GitHub CLI
      - go-yq # Portable command-line YAML processor
      - hub # cli interface for Github
      - jq # Command-line JSON processor
      - lazygit # Simple terminal UI for git commands
      - lf #  A terminal file manager inspired by ranger
      - lynx # A text browser for the World Wide Web
      - mediainfo # Supplies technical and tag information about a video or audio file (CLI interface)
      - neovim # Fork of Vim aiming to improve user experience, plugins, and GUIs
      - nmap # Utility for network discovery and security auditing
      - obsidian # A powerful knowledge base that works on top of a local folder of plain text Markdown files
      - openbsd-netcat # TCP/IP swiss army knife. OpenBSD variant.
      - p7zip # Command-line file archiver with high compression ratio
      - parallel # A shell tool for executing jobs in parallel
      - pcmanfm-gtk3 # Extremely fast and lightweight file manager (GTK+ 3 version)
      - rebuild-detector # Detects which packages need to be rebuilt
      - reflector # A Python 3 module and script to retrieve and filter the latest Pacman mirror list.
      - ripgrep # A search tool that combines the usability of ag with the raw speed of grep
      - rmlint # Tool to remove duplicates and other lint, being much faster than fdupes
      - rsync #  A fast and versatile file copying tool for remote and local files
      - starship # The cross-shell prompt for astronauts
      - thefuck # Magnificent app which corrects your previous console command
      - tmux # A terminal multiplexer
      - trash-cli # Command line trashcan (recycle bin) interface
      - unrar # The RAR uncompression program
      - unzip # For extracting and viewing files in .zip archives
      - websocat # Command-line client for web sockets, like netcat/curl/socat for ws://
      - wget # Network utility to retrieve files from the Web
      - which # A utility to show the full path of commands
      - zoxide # A smarter cd command for your terminal
      update_cache: yes
      state: latest
    become: true

  - name: "Set fish as default shell for current user"
    ansible.builtin.user:
      name: "{{ ansible_user_id }}"
      shell: /usr/bin/fish
    become: true

  - name: "Install disk utilities"
    community.general.pacman:
      name:
      - btrfs-progs # Btrfs filesystem utilities
      - lvm2 # Logical Volume Manager 2 utilities
      - mdadm # A tool for managing/monitoring Linux md device arrays, also known as Software RAID
      - ntfs-3g # NTFS filesystem driver and utilities
      - xfsprogs # XFS filesystem utilities
      state: latest
    become: true

  - name: "Set email for mdmonitor service"
    ansible.builtin.lineinfile:
      path: /etc/mdadm.conf
      regexp: '^#MAILADDR'
      line: 'MAILADDR root'
      state: present
    become: true

  - name: Instal Tmux Plugin Manager
    ansible.builtin.git:
      repo: https://github.com/tmux-plugins/tpm.git
      dest: ~/.config/tmux/plugins/tpm
