#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  vars:
    ansible_ask_become_pass: true
    configs:
    - stylua

  tasks:
  - name: "Create the `aur_builder` user"
    become: yes
    ansible.builtin.user:
      name: aur_builder
      create_home: yes
      group: wheel

  - name: "Allow the `aur_builder` user to run `sudo pacman` without a password"
    become: yes
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/11-install-aur_builder
      line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      create: yes
      validate: 'visudo -cf %s'

  - name: "Create symlink for configuration directories"
    ansible.builtin.file:
      src: "{{ playbook_dir }}/config/{{ item }}"
      dest: "~/.config/{{ item }}"
      state: link
      owner: 1000
      group: 1000
    loop: "{{ configs }}"

  - name: "Rust"
    community.general.pacman:
      name: 
      - base-devel
      - rust
      state: latest
    become: yes

  - name: "Paru"
    kewlfft.aur.aur:
      name: paru # Feature packed AUR helper
      state: latest
    become: yes
    become_user: aur_builder

  - name: "NPM"
    community.general.pacman:
      name: 
      - npm
      state: latest
    become: yes

  - name: "Instal Node version manager"
    community.general.npm:
      name: n
      global: yes
      state: latest
    become: yes

  - name: "Instal 'neovim' Node package"
    community.general.npm:
      name: neovim
      global: yes
      state: latest
    become: yes

  - name: "Instal 'neovim' Python package"
    ansible.builtin.pip:
      name:
      - neovim
      - virtualfish

  - name: "Lua"
    community.general.pacman:
      name: 
      - lua # Powerful lightweight programming language designed for extending applications
      - luarocks # Deployment and management system for Lua modules
      state: latest
    become: yes

  - name: "Ruby"
    community.general.pacman:
      name: 
      - ruby # An object-oriented language for quick and easy programming
      state: latest
    become: yes

  - name: "Linters"
    community.general.pacman:
      name:
      - eslint # An AST-based pattern checker for JavaScript
      - flake8 # The modular source code checker
      - prettier # An opinionated code formatter for JS, JSON, CSS, YAML and much more
      - python-black # Uncompromising Python code formatter
      state: latest
    become: yes

  - name: "Linters from AUR"
    kewlfft.aur.aur:
      name:
      - stylua # Code formatter for Lua
      state: latest
    become: yes
    become_user: aur_builder

  - name: "Install Git BFG"
    kewlfft.aur.aur:
      name:
      - bfg # Removes large or troublesome blobs like git-filter-branch does, but faster.
      state: latest
    become: yes
    become_user: aur_builder

  - name: "Install Git Filter Repo"
    community.general.pacman:
      name:
      - git-filter-repo # Quickly rewrite git repository history (filter-branch replacement)
      state: latest
    become: yes

  - name: "Install Krew"
    kewlfft.aur.aur:
      name: krew # Krew is the package manager for kubectl plugins
      state: latest
    become: yes
    become_user: aur_builder

  - name: "Install Google Cloud SDK And Plugins"
    kewlfft.aur.aur:
      name:
      - google-cloud-sdk # A set of command-line tools for the Google Cloud Platform. Includes gcloud (with beta and alpha commands), gsutil, and bq.
      - google-cloud-sdk-gke-gcloud-auth-plugin # A google-cloud-sdk component that provides a kubectl authentication plugin for GKE.
      state: latest
    become: yes
    become_user: aur_builder

  - name: "Packer"
    community.general.pacman:
      name:
      - packer # tool for creating identical machine images for multiple platforms from a single source configuration
      state: latest
    become: yes
...
