#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  vars:
    ansible_ask_become_pass: yes
    configs:
    - stylua

  tasks:
  - name: "Create the `aur_builder` user"
    become: yes
    ansible.builtin.user:
      name: aur_builder
      create_home: yes
      group: wheel

  - name: "Allow the `aur_builder` user to run `sudo pacman` without a password"
    become: yes
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/11-install-aur_builder
      line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      create: yes
      validate: 'visudo -cf %s'

  - name: "Create symlink for configuration directories"
    ansible.builtin.file:
      src: "{{ playbook_dir }}/config/{{ item }}"
      dest: "~/.config/{{ item }}"
      state: link
      owner: 1000
      group: 1000
    loop: "{{ configs }}"

  - name: "Rust"
    community.general.pacman:
      name: 
      - base-devel
      - rust
      state: latest
    become: yes

  - name: "Paru"
    kewlfft.aur.aur:
      name: paru
      state: latest
    become: yes
    become_user: aur_builder

  - name: "NPM"
    community.general.pacman:
      name: 
      - npm
      state: latest
    become: yes

  - name: "Instal Node version manager"
    community.general.npm:
      name: n
      global: yes
      state: latest
    become: yes

  - name: "Instal 'neovim' Node package"
    community.general.npm:
      name: neovim
      global: yes
      state: latest
    become: yes

  - name: "Instal 'neovim' Python package"
    ansible.builtin.pip:
      name:
      - neovim
      - virtualfish

  - name: "Lua"
    community.general.pacman:
      name: 
      - lua
      - luarocks
      state: latest
    become: yes

  - name: "Linters"
    community.general.pacman:
      name:
      - eslint
      - flake8
      - prettier
      - python-black
      state: latest
    become: yes

  - name: "Linters from AUR"
    kewlfft.aur.aur:
      name:
      - stylua
      state: latest
    become: yes
    become_user: aur_builder

  - name: "Install Git BFG"
    kewlfft.aur.aur:
      name:
      - bfg
      state: latest
    become: yes
    become_user: aur_builder

  - name: "Install Git Filter Repo"
    community.general.pacman:
      name:
      - git-filter-repo
      state: latest
    become: yes

  - name: "Install Krew"
    kewlfft.aur.aur:
      name: krew
      state: latest
    become: yes
    become_user: aur_builder

  - name: "Install Google Cloud SDK"
    kewlfft.aur.aur:
      name: google-cloud-sdk
      state: latest
    become: yes
    become_user: aur_builder
 
  - name: "Install Google Cloud SDK GKE Auth plugin"
    kewlfft.aur.aur:
      name: google-cloud-sdk-gke-gcloud-auth-plugin
      state: latest
    become: yes
    become_user: aur_builder
...
