#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  vars:
    ansible_ask_become_pass: yes
    configs:
    - awesome
    - picom
    - redshift

  tasks:
  - name: "Install Xorg"
    community.general.pacman:
      name: 
      - xorg
      - xorg-xinit
      - nvidia
      - nvidia-utils
      - nvidia-settings
      - xorg-fonts-100dpi
      - xclip
      state: latest
    become: yes

  - name: "Nerd Fonts"
    kewlfft.aur.aur:
      name:
      - nerd-fonts-complete
      - nerd-fonts-dejavu-complete
      - nerd-fonts-source-code-pro
      state: latest
    become: yes
    become_user: aur_builder

  - name: "Install Fonts"
    community.general.pacman:
      name: 
      - noto-fonts
      - noto-fonts-emoji
      - noto-fonts-cjk
      - noto-fonts-extra
      update_cache: yes
      state: latest
    become: yes

  - name: "Create symlinks for configurations"
    ansible.builtin.file:
      src: "{{ playbook_dir }}/config/{{ item }}"
      dest: "~/.config/{{ item }}"
      state: link
      owner: 1000
      group: 1000
    loop: "{{ configs }}"

  - name: "Install Awesome"
    community.general.pacman:
      name: 
      - awesome
      - picom
      update_cache: yes
      state: latest
    become: yes

  - name: "Install Auxiliary WM applications"
    community.general.pacman:
      name: 
      - dmenu
      - clipmenu
      update_cache: yes
      state: latest
    become: yes

  - name: "Install LightDM"
    community.general.pacman:
      name: 
      - lightdm
      - lightdm-slick-greeter
      state: latest
    become: yes

  - name: "Configure Greeter for LightDM"
    ansible.builtin.lineinfile:
      path: /etc/lightdm/lightdm.conf
      regexp: "#greeter-session="
      line: greeter-session=lightdm-slick-greeter
    become: yes

  - name: "Enable LightDM"
    ansible.builtin.systemd:
      name: lightdm
      enabled: yes
    become: yes

  - name: "Install Redshift"
    community.general.pacman:
      name: 
      - redshift
      update_cache: yes
      state: latest
    become: yes
...
