#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  vars:
    ansible_ask_become_pass: true
    configs:
    - awesome
    - gammastep
    - hypr
    - mako
    - niri
    - picom
    - redshift
    - rofi
    - waybar

  tasks:
  - name: "Install Xorg"
    community.general.pacman:
      name:
      - xorg
      - xorg-xinit # X.Org initialisation program
      - mesa # An open-source implementation of the OpenGL specification
      - vulkan-radeon # Radeon's Vulkan mesa driver
      - xorg-fonts-100dpi # X.org 100dpi fonts
      - xclip # Command line interface to the X11 clipboard
      - upower # Abstraction for enumerating power devices, listening to device events and querying history and statistics
      - arandr # Provide a simple visual front end for XRandR 1.2.
      - autorandr # Auto-detect connected display hardware and load appropiate X11 setup using xrandr
      state: latest
    become: true

  - name: "Install Wayland"
    community.general.pacman:
      name:
      - wayland # A computer display server protocol
      - xorg-xwayland # run X clients under wayland
      - wayland-protocols # Specifications of extended Wayland protocols
      - wl-clipboard # Command-line copy/paste utilities for Wayland
      - libva # Video Acceleration (VA) API for Linux
      - wlr-randr # Utility to manage outputs of a Wayland compositor
      - xwayland-satellite # Xwayland outside your Wayland
      - qt5-wayland # Provides APIs for Wayland
      - qt6-wayland # Provides APIs for Wayland
      - xdg-desktop-portal-gnome # Backend implementation for xdg-desktop-portal for the GNOME desktop environment
      - xdg-desktop-portal-gtk # A backend implementation for xdg-desktop-portal using GTK
      - xdg-desktop-portal-wlr # xdg-desktop-portal backend for wlroots
      - xdg-desktop-portal-hyprland # xdg-desktop-portal backend for hyprland
      state: latest
    become: true

  - name: "Install Greetd"
    community.general.pacman:
      name:
      - greetd # Generic greeter daemon
      - greetd-regreet # Clean and customizable greeter for greetd
      - cage # A kiosk compositor for Wayland
      state: latest
    become: true

  - name: "Install Niri"
    community.general.pacman:
      name:
      - niri # A scrollable-tiling Wayland compositor
      state: latest
    become: true

  - name: "Copy greetd configuration"
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/config/greetd/{{ item }}"
      dest: "/etc/greetd/"
      group: greeter
      owner: greeter
    become: true
    loop:
    - "config.toml"
    - "regreet.toml"

  - name: "Copy greetd startup script"
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/config/greetd/cage.sh"
      dest: "/usr/local/bin/"
      group: greeter
      owner: greeter
    become: true

  - name: "Enable SDDM"
    ansible.builtin.systemd:
      name: sddm
      enabled: false
    become: true

  - name: "Enable greetd"
    ansible.builtin.systemd:
      name: greetd
      enabled: true
    become: true

  - name: "Install Waybar"
    community.general.pacman:
      name:
      - waybar # Highly customizable Wayland bar for Sway and Wlroots based compositors
      update_cache: true
      state: latest
    become: true

  - name: "Install ndrop"
    kewlfft.aur.aur:
      name:
      - ndrop-git # Run, show and hide programs via keybind in niri
      state: absent
    become: true
    become_user: aur_builder

  - name: "Install swww"
    community.general.pacman:
      name:
      - swww # Highly customizable Wayland bar for Sway and Wlroots based compositors
      update_cache: true
      state: latest
    become: true

  - name: "Enable Autorandr"
    ansible.builtin.systemd:
      name: autorandr
      enabled: true
    become: true

  - name: "Lookup for HiDPI configs"
    ansible.builtin.find:
      paths: "{{ playbook_dir }}/config/hidpi"
      hidden: true
    register: hidpi

  - name: "Create symlinks for configurations"
    ansible.builtin.file:
      src: "{{ playbook_dir }}/config/hidpi/{{ item.path | basename }}"
      dest: "~/{{ item.path | basename }}"
      state: link
      owner: 1000
      group: 1000
    loop: "{{ hidpi.files }}"

  - name: "Install Fonts"
    community.general.pacman:
      name:
      - noto-fonts # Google Noto TTF fonts
      - noto-fonts-emoji # Google Noto emoji fonts
      - noto-fonts-cjk # Google Noto CJK fonts
      - noto-fonts-extra # Google Noto TTF fonts - additional variants
      - ttf-ubuntu-mono-nerd # Patched font Ubuntu Mono from nerd fonts library
      - ttf-ubuntu-nerd # Patched font Ubuntu from nerd fonts library
      - ttf-dejavu-nerd # Patched font Dejavu Sans Mono from nerd fonts library
      - ttf-firacode-nerd # Patched font Fira (Fura) Code from nerd fonts library
      - ttf-nerd-fonts-symbols # High number of extra glyphs from popular 'iconic fonts'
      - ttf-nerd-fonts-symbols-common # High number of extra glyphs from popular 'iconic fonts' (common files)
      - ttf-nerd-fonts-symbols-mono # High number of extra glyphs from popular 'iconic fonts' (monospace)
      - ttf-noto-nerd # Patched font Noto from nerd fonts library
      - otf-firamono-nerd # Patched font Fira (Fura) Mono from nerd fonts library
      update_cache: true
      state: latest
    become: true

  - name: "Install Ubuntu Mono Ligaturized"
    kewlfft.aur.aur:
      name:
      - ttf-ubuntu-mono-ligaturized-git
      state: latest
    become: true
    become_user: aur_builder

  - name: "Create symlinks for configurations"
    ansible.builtin.file:
      src: "{{ playbook_dir }}/config/{{ item }}"
      dest: "~/.config/{{ item }}"
      state: link
      owner: 1000
      group: 1000
    loop: "{{ configs }}"

  - name: "Install Awesome WM"
    kewlfft.aur.aur:
      name:
      - awesome-git # Highly configurable framework window manager
      state: latest
    become: true
    become_user: aur_builder

  - name: "Install Picom"
    community.general.pacman:
      name:
      - picom # X compositor that may fix tearing issues
      update_cache: true
      state: latest
    become: true

  - name: "Install Auxiliary WM applications"
    community.general.pacman:
      name:
      - dmenu # Generic menu for X
      - clipmenu # Clipboard management using dmenu
      update_cache: true
      state: latest
    become: true

  - name: "Install SDDM"
    community.general.pacman:
      name:
      - sddm # QML based X11 and Wayland display manager
      state: latest
    become: true

  - name: "Install SDDM theme"
    kewlfft.aur.aur:
      name:
      - sddm-sugar-dark
      state: latest
    become: true
    become_user: aur_builder

  - name: "Copy SDDM configuration"
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/config/sddm/"
      dest: "/etc/sddm.conf.d/"
    become: true

  - name: "Install Rofi"
    community.general.pacman:
      name:
      - rofi # A window switcher, application launcher and dmenu replacement
      state: latest
    become: true

  - name: "Pinentry for Rofi"
    kewlfft.aur.aur:
      name:
      - pinentry-rofi # rofi-based pinentry implementation
      state: latest
    become: true
    become_user: aur_builder

  - name: "Install Vicinae"
    kewlfft.aur.aur:
      name:
      - vicinae-bin # A focused launcher for your desktop — native, fast, extensible
    become: true
    become_user: aur_builder

  - name: Enable vicinae
    ansible.builtin.systemd:
      name: vicinae
      state: started
      enabled: true
      scope: user

  - name: "Clipboard"
    kewlfft.aur.aur:
      name:
      - clipboard # Cut, copy, and paste anything in your terminal.
      state: latest
    become: true
    become_user: aur_builder

  - name: "Install FFmpegthumbnailer"
    community.general.pacman:
      name:
      - ffmpegthumbnailer # Lightweight video thumbnailer that can be used by file managers
      state: latest
    become: true

  - name: "Symlink .gnupg configuration"
    ansible.builtin.file:
      src: "{{ playbook_dir }}/config/gnupg/gpg-agent.conf"
      dest: "~/.gnupg/gpg-agent.conf"
      state: link
      owner: 1000
      group: 1000

  - name: "Install gammastep"
    community.general.pacman:
      name:
      - gammastep  # Adjusts the color temperature of your screen according to your surroundings.
      update_cache: true
      state: latest
    become: true

  - name: Enable gammastep
    ansible.builtin.systemd:
      name: gammastep
      state: started
      enabled: true
      scope: user

  - name: "Install hypridle"
    community.general.pacman:
      name:
      - hypridle  # Idle management daemon for Wayland
      - swayidle  # Idle management daemon for Wayland
      - hyprland-protocols
      update_cache: true
      state: latest
    become: true

  - name: "Install mako"
    community.general.pacman:
      name:
      - mako
      update_cache: true
      state: latest
    become: true

  - name: "Enable mako for the niri user session"
    ansible.builtin.systemd_service:
      name: mako.service
      scope: user
      enabled: true
      state: started

  - name: "Enable hypridle"
    ansible.builtin.systemd:
      name: hypridle
      state: started
      enabled: true
      scope: user

  - name: "Install Redshift"
    community.general.pacman:
      name:
      - redshift # Adjusts the color temperature of your screen according to your surroundings.
      update_cache: true
      state: latest
    become: true

  - name: Enable Redshift
    ansible.builtin.systemd:
      name: redshift
      state: stopped
      enabled: false
      scope: user
