#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  vars:
    ansible_ask_become_pass: yes
    configs:
    - awesome
    - picom
    - redshift

  tasks:
  - name: "Install Xorg"
    community.general.pacman:
      name: 
      - xorg
      - xorg-xinit # X.Org initialisation program
      - nvidia # NVIDIA drivers for linux
      - nvidia-utils # NVIDIA drivers utilities
      - nvidia-settings # Tool for configuring the NVIDIA graphics driver
      - xorg-fonts-100dpi # X.org 100dpi fonts
      - xclip # Command line interface to the X11 clipboard
      - upower # Abstraction for enumerating power devices, listening to device events and querying history and statistics
      state: latest
    become: yes

  - name: "Nerd Fonts"
    kewlfft.aur.aur:
      name:
      - nerd-fonts-complete # Iconic font aggregator, collection, & patcher. 3,600+ icons, 50+ patched fonts.
      - nerd-fonts-dejavu-complete # All variants of Nerd-Font-patched DejaVu Sans Mono
      - nerd-fonts-source-code-pro # Patched font SourceCodePro from nerd-fonts library
      state: latest
    become: yes
    become_user: aur_builder

  - name: "Install Fonts"
    community.general.pacman:
      name: 
      - noto-fonts # Google Noto TTF fonts
      - noto-fonts-emoji # Google Noto emoji fonts
      - noto-fonts-cjk # Google Noto CJK fonts
      - noto-fonts-extra # Google Noto TTF fonts - additional variants
      update_cache: yes
      state: latest
    become: yes

  - name: "Create symlinks for configurations"
    ansible.builtin.file:
      src: "{{ playbook_dir }}/config/{{ item }}"
      dest: "~/.config/{{ item }}"
      state: link
      owner: 1000
      group: 1000
    loop: "{{ configs }}"

  - name: "Install Awesome"
    community.general.pacman:
      name: 
      - awesome # Highly configurable framework window manager
      - picom # X compositor that may fix tearing issues
      update_cache: yes
      state: latest
    become: yes

  - name: "Install Auxiliary WM applications"
    community.general.pacman:
      name: 
      - dmenu # Generic menu for X
      - clipmenu # Clipboard management using dmenu
      update_cache: yes
      state: latest
    become: yes

  - name: "Install LightDM"
    community.general.pacman:
      name: 
      - lightdm # A lightweight display manager
      - lightdm-slick-greeter # A slick-looking LightDM greeter
      state: latest
    become: yes

  - name: "Configure Greeter for LightDM"
    ansible.builtin.lineinfile:
      path: /etc/lightdm/lightdm.conf
      regexp: "#greeter-session="
      line: greeter-session=lightdm-slick-greeter
    become: yes

  - name: "Enable LightDM"
    ansible.builtin.systemd:
      name: lightdm
      enabled: yes
    become: yes

  - name: "Install Redshift"
    community.general.pacman:
      name: 
      - redshift # Adjusts the color temperature of your screen according to your surroundings.
      update_cache: yes
      state: latest
    become: yes

  - name: Enable Redshift
    ansible.builtin.systemd:
      name: redshift
      state: started
      enabled: yes
      scope: user
...
