#!/usr/bin/env ansible-playbook
---
- name: "Install game development tools"
  hosts: localhost
  vars:
    ansible_ask_become_pass: true

  tasks:
  - name: Install "bevy" Rust package
    community.general.cargo:
      name: bevy
