#!/usr/bin/env ansible-playbook
---
- hosts: localhost

  tasks:
  - name: "Create symlink for Git configuration"
    ansible.builtin.file:
      src: "{{ playbook_dir }}/git"
      dest: ~/.config/git
      state: link
      owner: 1000
      group: 1000

  - name: "Create symlink for NeoVim configuration"
    ansible.builtin.file:
      src: "{{ playbook_dir }}/nvim"
      dest: ~/.config/nvim
      state: link
      owner: 1000
      group: 1000

  - name: "Create symlink for awesome configuration"
    ansible.builtin.file:
      src: "{{ playbook_dir }}/awesome"
      dest: ~/.config/awesome
      state: link
      owner: 1000
      group: 1000
