#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  vars:
    ansible_connection: local

  tasks:
  - name: "Create symlink for Git configuration"
    ansible.builtin.file:
      src: "{{ playbook_dir }}/git"
      dest: ~/.config/git
      state: link
      owner: 1000
      group: 1000
