#!/usr/bin/env ansible-playbook
---
- hosts: localhost

  tasks:
  - name: "Install Downgrade"
    kewlfft.aur.aur:
      name: downgrade
      state: latest
    become: true
    become_user: aur_builder

  - name: "Install Brave browser"
    kewlfft.aur.aur:
      name: brave-bin
      state: latest
    become: true
    become_user: aur_builder

  - name: "Install Zoom"
    kewlfft.aur.aur:
      name: zoom
      state: latest
    become: true
    become_user: aur_builder

  - name: "Install TLDR"
    kewlfft.aur.aur:
      name: tlrc-bin
      state: latest
    become: true
    become_user: aur_builder

  - name: "Install OBS"
    community.general.pacman:
      name:
      - obs-studio
      state: latest
    become: true

  - name: "Install CUPS"
    community.general.pacman:
      name:
      - cups
      state: latest
    become: true

  - name: "Enable CUPS"
    ansible.builtin.systemd:
      name: cups
      state: started
      enabled: true
    become: true

  - name: "Install SANE"
    community.general.pacman:
      name:
      - sane
      state: latest
    become: true

  - name: "Install Skanpage"
    community.general.pacman:
      name:
      - skanpage
      state: latest
    become: true

  - name: "Install PacCap"
    community.general.pacman:
      name:
      - tcpdump
      - wireshark-qt
      - wireshark-cli
      - termshark
      state: latest
    become: true

  - name: "Install LibreOffice"
    community.general.pacman:
      name:
      - libreoffice-fresh
      - libreoffice-fresh-ru
      state: latest
    become: true

  - name: "Install VPN clients"
    community.general.pacman:
      name:
      - openvpn # An easy-to-use, robust and highly configurable VPN (Virtual Private Network)
      - wireguard-tools # next generation secure network tunnel - tools for configuration
      update_cache: true
      state: latest
    become: true

  - name: "Install sing-geoip"
    kewlfft.aur.aur:
      name: sing-geoip-git
      state: latest
    become: true
    become_user: aur_builder

  - name: "Install sing-geoip-db"
    kewlfft.aur.aur:
      name: sing-geoip-db-git
      state: latest
    become: true
    become_user: aur_builder

  - name: "Install sing-geosite"
    kewlfft.aur.aur:
      name: sing-geosite-git
      state: latest
    become: true
    become_user: aur_builder

  - name: "Install sing-geosite-db"
    kewlfft.aur.aur:
      name: sing-geosite-db-git
      state: latest
    become: true
    become_user: aur_builder

  - name: "Install ExpressVPN"
    kewlfft.aur.aur:
      name: expressvpn
      state: latest
    become: true
    become_user: aur_builder
