#!/usr/bin/env ansible-playbook
---
- name: "Install miscellaneous packages"
  hosts: localhost

  tasks:
  - name: "Install Downgrade"
    kewlfft.aur.aur:
      name: downgrade # Bash script for downgrading one or more packages to a version in your cache or the A.L.A.
      state: latest
    become: true
    become_user: "{{ aur_builder_user }}"

  - name: "Install Brave browser"
    kewlfft.aur.aur:
      name: brave-bin # Web browser that blocks ads and trackers by default
      state: latest
    become: true
    become_user: "{{ aur_builder_user }}"

  - name: "Install Zoom"
    kewlfft.aur.aur:
      name: zoom # Video Conferencing and Web Conferencing Service
      state: latest
    become: true
    become_user: "{{ aur_builder_user }}"

  - name: "Install TLDR"
    kewlfft.aur.aur:
      name: tlrc-bin # Official tldr client written in Rust
      state: latest
    become: true
    become_user: "{{ aur_builder_user }}"

  - name: "Install OBS"
    community.general.pacman:
      name:
      - obs-studio # Free, open source software for live streaming and recording
      state: latest
    become: true

  - name: "Install CUPS"
    community.general.pacman:
      name:
      - cups # OpenPrinting CUPS - daemon package
      state: latest
    become: true

  - name: "Enable CUPS"
    ansible.builtin.systemd:
      name: cups
      state: started
      enabled: true
    become: true

  - name: "Install SANE"
    community.general.pacman:
      name:
      - sane # Scanner Access Now Easy
      state: latest
    become: true

  - name: "Install Skanpage"
    community.general.pacman:
      name:
      - skanpage # Utility to scan images and multi-page documents
      state: latest
    become: true

  - name: "Install PacCap"
    community.general.pacman:
      name:
      - tcpdump # Powerful command-line packet analyzer
      - wireshark-qt # Network traffic and protocol analyzer/sniffer - Qt GUI
      - wireshark-cli # Network traffic and protocol analyzer/sniffer - CLI tools and data files
      - termshark # Terminal UI for tshark, inspired by Wireshark
      state: latest
    become: true

  - name: "Install LibreOffice"
    community.general.pacman:
      name:
      - libreoffice-fresh # LibreOffice branch which contains new features and program enhancements
      - libreoffice-fresh-ru # Russian language pack for LibreOffice Fresh
      state: latest
    become: true

  - name: "Install VPN clients"
    community.general.pacman:
      name:
      - openvpn # An easy-to-use, robust and highly configurable VPN (Virtual Private Network)
      - wireguard-tools # next generation secure network tunnel - tools for configuration
      - vortix # A TUI for WireGuard and OpenVPN with real-time telemetry and leak guarding
      - v2ray # A platform for building proxies to bypass network restrictions
      state: latest
    become: true

  - name: "Install VLESS apps"
    kewlfft.aur.aur:
      name:
      - v2raya-bin # A web GUI client of Project V which supports VMess, VLESS, SS, SSR, Trojan, Tuic and Juicity protocols
      - sing-geoip-rule-set-git # GeoIP Rule Sets for sing-box
      - sing-geosite-rule-set-git # Geosite Rule Sets for sing-box
      - flclashx-bin # Fork of FlClash | A multi-platform proxy client based on ClashMeta, simple and easy to use, open-source and ad-free.
      - clash-verge-rev-bin # Continuation of Clash Verge | A Clash Meta GUI based on Tauri
      use: "{{ aur_helper }}"
      state: latest
    become: true
    become_user: "{{ aur_builder_user }}"

  - name: "Install ExpressVPN"
    kewlfft.aur.aur:
      name:
      - expressvpn # Proprietary VPN client for Linux
      state: latest
    become: true
    become_user: "{{ aur_builder_user }}"

  - name: "Install XFR"
    kewlfft.aur.aur:
      name:
      - xfr-bin # A modern iperf3 alternative with a live TUI, multi-client server, and QUIC support
      state: latest
    become: true
    become_user: "{{ aur_builder_user }}"

  - name: "Install Trippy"
    community.general.pacman:
      name:
      - trippy # A network diagnostic tool
      state: latest
    become: true
