#!/usr/bin/env ansible-playbook
---
- hosts: localhost

  tasks:
  - name: "Install Brave browser"
    kewlfft.aur.aur:
      name: brave-bin
      state: latest
    become: yes
    become_user: aur_builder

  - name: "Install Zoom"
    kewlfft.aur.aur:
      name: zoom
      state: latest
    become: yes
    become_user: aur_builder

  - name: "Install Wireguard-Tools"
    community.general.pacman:
      name:
      - wireguard-tools
      state: latest
    become: yes

  - name: "Install OBS"
    community.general.pacman:
      name: 
      - obs-studio
      state: latest
    become: yes

  - name: "Install CUPS"
    community.general.pacman:
      name:
      - cups
      state: latest
    become: yes

  - name: "Enable CUPS"
    ansible.builtin.systemd:
      name: cups
      state: started
      enabled: yes
    become: yes

  - name: "Install SANE"
    community.general.pacman:
      name:
      - sane
      state: latest
    become: yes

  - name: "Install Skanpage"
    community.general.pacman:
      name:
      - skanpage
      state: latest
    become: yes

  - name: "Install PacCap"
    community.general.pacman:
      name:
      - tcpdump
      - wireshark-qt
      - wireshark-cli
      - termshark
      state: latest
    become: yes
...
