#!/usr/bin/env ansible-playbook
---
- name: Install and configure common packages
  import_playbook: common.yaml
- import_playbook: dev-tools.yaml
- import_playbook: display.yaml
- import_playbook: audio.yaml
- import_playbook: apps.yaml
...
