#!/usr/bin/env ansible-playbook
---
- name: "Install and configure common packages"
  import_playbook: common.yaml
- name: "Install developer tools"
  import_playbook: dev-tools.yaml
- name: "Install GUI tools and Apps"
  import_playbook: display.yaml
- name: "Install Audio Apps and Utilities"
  import_playbook: audio.yaml
- name: "Install different Applications"
  import_playbook: apps.yaml
- name: "Virtualization Utilities and Tools"
  import_playbook: virt.yaml
- name: "Other Apps"
  import_playbook: misc.yaml
...
