#!/usr/bin/env ansible-playbook
- hosts: localhost
  vars:
    ansible_ask_become_pass: true
    configs:
    - k9s
    - nix

  tasks:
  - name: "Create symlink for configuration directories"
    ansible.builtin.file:
      src: "{{ playbook_dir }}/config/{{ item }}"
      dest: "~/.config/{{ item }}"
      state: link
      owner: 1000
      group: 1000
    loop: "{{ configs }}"

  - name: "Install Docker tools"
    community.general.pacman:
      name:
      - buildkit # A toolkit for converting source code to build artifacts in a repeatable manner
      - cilium-cli # install, manage & troubleshoot Kubernetes clusters running Cilium
      - docker # Pack, ship and run any application as a lightweight container
      - dive # A tool for exploring layers in a docker image
      - ducker # A terminal app for managing docker containers
      - docker-buildx # Docker CLI plugin for extended build capabilities with BuildKit
      - docker-compose # Fast, isolated development environments using Docker
      - helm # The Kubernetes Package Manager
      - k9s # TUI for managing Kubernetes clusters and pods
      - kubectl # A command line tool for communicating with a Kubernetes API server
      - kubectx # Utility to manage and switch between kubectl contexts and Kubernetes namespaces
      - nix # A purely functional package manager
      - podman # Tool and library for running OCI-based containers in pods
      - podman-compose # A script to run docker-compose.yml using podman
      - skopeo # A command line utility for various operations on container images and image repositories.
      state: latest
    become: true

  - name: "Install Kubecolor"
    kewlfft.aur.aur:
      name:
      - kubecolor
      state: latest
    become: true
    become_user: aur_builder

  - name: "Set subuids for Podman"
    ansible.builtin.lineinfile:
      path: "/etc/subuid"
      regexp: "{{ ansible_facts['user_id'] }}"
      line: "{{ ansible_facts['user_id'] }}:100000:65535"
      backup: true
    become: true

  - name: "Set subgids for Podman"
    ansible.builtin.lineinfile:
      path: "/etc/subgid"
      regexp: "{{ ansible_facts['user_id'] }}"
      line: "{{ ansible_facts['user_id'] }}:100000:65535"
      backup: true
    become: true

  - name: "Copy Docker Configuration file"
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/config/docker/daemon.json"
      dest: /etc/docker/daemon.json
      mode: "0644"
    become: true

  - name: "Install lazydocker"
    kewlfft.aur.aur:
      name:
      - lazydocker # A simple terminal UI for docker and docker-compose, written in Go with the gocui library.
      state: latest
    become: true
    become_user: aur_builder

  - name: "Enable nested virtualization"
    community.general.modprobe:
      name: kvm_amd
      params: "nested=1"
      state: present
    become: true

  - name: "Install Libvirt and Virtualization tools"
    community.general.pacman:
      name:
      - libvirt # API for controlling virtualization engines (openvz,kvm,qemu,virtualbox,xen,etc)
      - qemu-base # A basic QEMU setup for headless environments
      - dmidecode # Desktop Management Interface table related utilities
      - dnsmasq # Lightweight, easy to configure DNS forwarder and DHCP server
      state: latest
    become: true

  - name: "Install Additional tools for libvirt"
    community.general.pacman:
      name:
      - virt-install # Command line tool for creating new KVM , Xen, or Linux container guests using the libvirt hypervisor
      - virt-viewer # A lightweight interface for interacting with the graphical display of virtualized guest OS.
      - libguestfs # Access and modify virtual machine disk images
      state: latest
    become: true

  - name: "Install DevOps tools"
    community.general.pacman:
      name:
      - minikube # A tool that makes it easy to run Kubernetes locally
      - vagrant # Build and distribute virtualized development environments
      state: latest
    become: true

  - name: "Install Icedtea-web"
    community.general.pacman:
      name:
      - icedtea-web
      state: latest
    become: true

  - name: "Set the UNIX domain socket group ownership to libvirt"
    ansible.builtin.lineinfile:
      path: /etc/libvirt/libvirtd.conf
      regexp: '^#unix_sock_group'
      line: 'unix_sock_group = "libvirt"'
      state: present
    become: true

  - name: "Set the UNIX domain socket group ownership to libvirt"
    ansible.builtin.lineinfile:
      path: /etc/libvirt/libvirtd.conf
      regexp: '^#unix_sock_rw_perms'
      line: 'unix_sock_rw_perms = "0770"'
      state: present
    become: true

  - name: "Install Cockpit"
    community.general.pacman:
      name:
      - cockpit # A systemd web based user interface for Linux servers
      - cockpit-machines # Cockpit UI for virtual machines
      - cockpit-podman # Cockpit UI for podman containers
      - cockpit-pcp # Cockpit support for reading PCP metrics and loading PCP archives
      - cockpit-storaged # Cockpit user interface for storage, using udisks
      - cockpit-docker # Cockpit UI for docker containers
      state: latest
    become: true

  - name: "Install Cockpit plugins from AUR"
    kewlfft.aur.aur:
      name:
      - cockpit-zfs-manager # An interactive ZFS on Linux admin package for Cockpit
      - cockpit-file-sharing # A Cockpit plugin to easily manage samba and NFS file sharing.
      - cockpit-navigator # A Featureful File Browser for Cockpit
      - cockpit-pacman # Cockpit plugin for Arch Linux package management using alpm.rs
      state: latest
    become: true
    become_user: aur_builder

  - name: "Install kind for kubernetes"
    kewlfft.aur.aur:
      name:
      - kind # Kubernetes IN Docker - local clusters for testing Kubernetes
      state: latest
    become: true
    become_user: aur_builder

  - name: "Configure groups for current user"
    ansible.builtin.user:
      name: "{{ ansible_facts['user_id'] }}"
      groups: "{{ item }}"
      append: true
    become: true
    loop:
    - docker
    - libvirt
    - nix-users
    - nixbld

  - name: "Enable Docker"
    ansible.builtin.systemd:
      name: "{{ item }}"
      state: started
      enabled: true
    become: true
    loop:
    - cockpit.socket
    - docker.socket
    - libvirtd.socket
    - nix-daemon.socket
    - podman.socket

  - name: "Install oxker"
    kewlfft.aur.aur:
      name:
      - oxker # A simple TUI to view & control Docker containers
      state: latest
    become: true
    become_user: aur_builder
