# Ly display manager configuration
# Full reference: /etc/ly/config.ini.example

animation = matrix
#animation = doom

bigclock = en
bigclock_seconds = true

numlock = true

hide_version_string = true

save = true

vi_mode = true
vi_default_mode = insert
