#Do not add new line

add_newline = false
scan_timeout = 30

[directory]
fish_style_pwd_dir_length = 3

[line_break]
disabled = false

[character]
error_symbol = "[✖](bold red)"

[time]
disabled = true

[gcloud]
format = ' [$symbol$active]($style) '

[kubernetes]
disabled = false
