[[manager.prepend_keymap]]
on   = "!"
run  = 'shell "$SHELL" --block'
desc = "Open shell here"

[[manager.prepend_keymap]]
on = [ "g", "r" ]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
desc = "cd back to the root of the current Git repository"

[[manager.prepend_keymap]]
on = [ "<C-s>" ]
run = 'shell tmux_term_pane.sh'
desc = "cd back to the root of the current Git repository"

[[manager.prepend_keymap]]
on = [ "<S-t>" ]
run = 'plugin tmux-subpane'
desc = "cd back to the root of the current Git repository"

[[manager.prepend_keymap]]
on = [ "m" ]
run = "plugin bookmarks save"
desc = "Save current position as a bookmark"

[[manager.prepend_keymap]]
on = [ "'" ]
run = "plugin bookmarks jump"
desc = "Jump to a bookmark"

[[manager.prepend_keymap]]
on = [ "b", "d" ]
run = "plugin bookmarks delete"
desc = "Delete a bookmark"

[[manager.prepend_keymap]]
on = [ "b", "D" ]
run = "plugin bookmarks delete_all"
desc = "Delete all bookmarks"

# [[manager.prepend_keymap]]
# on = ["z", "h"]
# run = "plugin time-travel --args=prev"
# desc = "Go to previous snapshot"
#
# [[manager.prepend_keymap]]
# on = ["z", "l"]
# run = "plugin time-travel --args=next"
# desc = "Go to next snapshot"
#
# [[manager.prepend_keymap]]
# on = ["z", "e"]
# run = "plugin time-travel --args=exit"
# desc = "Exit browsing snapshots"
#
[[manager.prepend_keymap]]
on = [ "P", "s" ]
run = "plugin projects save"
desc = "Save current project"

[[manager.prepend_keymap]]
on = [ "P", "l" ]
run = "plugin projects load"
desc = "Load project"

[[manager.prepend_keymap]]
on = [ "P", "P" ]
run = "plugin projects load_last"
desc = "Load last project"

[[manager.prepend_keymap]]
on = [ "P", "d" ]
run = "plugin projects delete"
desc = "Delete project"

[[manager.prepend_keymap]]
on = [ "P", "D" ]
run = "plugin projects delete_all"
desc = "Delete all projects"

[[manager.prepend_keymap]]
on = [ "P", "m" ]
run = "plugin projects 'merge current'"
desc = "Merge current tab to other projects"

[[manager.prepend_keymap]]
on = [ "P", "M" ]
run = "plugin projects 'merge all'"
desc = "Merge current project to other projects"

[[manager.prepend_keymap]]
on   = [ ">" ]
run  = "plugin what-size"
desc = "Calc size of selection or cwd"

[[manager.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin lazygit"
desc = "run lazygit"

[[manager.prepend_keymap]]
on = [ "L" ]
run = "plugin bypass"
desc = "Recursively enter child directory, skipping children with only a single subdirectory"

[[manager.prepend_keymap]]
on = [ "H" ]
run = "plugin bypass reverse"
desc = "Recursively enter parent directory, skipping parents with only a single subdirectory"

[[manager.prepend_keymap]]
on = [ "l" ]
run = "plugin bypass smart_enter"
desc = "Open a file, or recursively enter child directory, skipping children with only a single subdirectory"

[[manager.prepend_keymap]]
on = "<C-y>"
run = ["plugin system-clipboard"]
desc = "Yank to System clipboard"
