[mgr]
ratio = [15, 40, 50 ]

[[plugin.prepend_previewers]]
url  = "*.service"
run  = 'piper -- bat -p --color=always "$1"'

[[plugin.prepend_previewers]]
url  = "*.socket"
run  = 'piper -- bat -p --color=always "$1"'

[[plugin.prepend_previewers]]
url  = "*.tar*"
run  = 'piper --format=url -- tar tf "$1"'

[[plugin.prepend_previewers]]
url = "*/"
# run = 'piper -- eza -TL=3 --color=always --icons=always --group-directories-first --no-quotes "$1"'
run = "eza-preview"

[[plugin.prepend_fetchers]]
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
url   = "*/"
run   = "git"
group = "git"

[[plugin.prepend_previewers]]
mime = "application/bittorrent"
run = "torrent-preview"

[[plugin.prepend_previewers]]
url  = "*.md"
run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"'

[[plugin.prepend_previewers]]
mime = "application/{,g}zip"
run  = "lsar"

[[plugin.prepend_previewers]]
mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}"
run  = "lsar"

[[plugin.prepend_spotters]]
url = "*"
run = "file-extra-metadata"

[tasks]
image_bound = [ 9000, 9000 ]

[preview]
cache_dir       = "~/.cache/yazi"
