aliases:
  dp: deployments
  sec: v1/secrets
  jo: jobs
  cr: clusterroles
  crb: clusterrolebindings
  ro: roles
  rb: rolebindings
  np: networkpolicies
  um: urlmaps.compute.gcp.m.upbound.io
  rneg: regionnetworkendpointgroups.compute.gcp.m.upbound.io
  bs: backendservices.compute.gcp.m.upbound.io
  gfr: globalforwardingrules.compute.gcp.m.upbound.io
  thp: targethttpproxies.compute.gcp.m.upbound.io
  rs: runservices.run.cnrm.cloud.google.com
  ed: xedgestacks.funnelflux.pro
  dd: xdevicedetectors.funnelflux.pro
  df: xdragonflies.funnelflux.pro
  xcr: xcloudruns.funnelflux.pro
